import React from 'react';
import Head from 'next/head';
import styles from '../styles/About.module.css';

const About = () => (
  <div className={styles.container}>
    <Head>
      <title>About - Hunting Coder</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="keywords" content="nextjs, hunting coder, hunting coder blog" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <h1 className={styles.heading}>About Hunting Coder</h1>

    <main className={styles.main}>
      <div>
        <h2>Introduction</h2>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore id architecto eos odit saepe dicta unde, rerum eligendi totam quibusdam fuga adipisci iusto doloremque? Quo ipsum aliquid incidunt! Atque voluptatem doloribus iste soluta dolorum commodi illum vel consequatur maiores distinctio! Omnis illum, tempora placeat necessitatibus quas pariatur magni veniam rerum maiores. Obcaecati laborum porro eaque commodi tenetur, facilis, vitae a accusantium mollitia nemo optio iste dignissimos maiores laboriosam placeat natus consequatur reiciendis cupiditate. Laboriosam provident nulla ut non sunt dicta, autem itaque pariatur quasi, qui beatae, omnis alias magnam commodi nostrum? Unde sunt delectus vitae ad enim, necessitatibus veniam cupiditate?</p>
      </div>

      <div>
        <h2>Services</h2>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos modi voluptatibus sapiente! Saepe nam veniam sit sequi! Officiis quod harum animi. Fugiat nostrum labore, doloribus, vero dignissimos iste aut accusantium similique atque voluptatem tempore.</p>

        <p>We offer the following services:</p>
        <ul>
          <li>Bloging</li>
          <li>Contacting</li>
          <li>Publishing</li>
        </ul>

      </div>

      <div>
        <h2>Contact us</h2>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore optio quae corporis, fugit, obcaecati vel quas repellendus hic et exercitationem assumenda deleniti nam velit, accusamus sint autem ipsum architecto maxime nisi voluptatem. Velit doloribus totam deserunt culpa ea, veritatis officia, quasi, consectetur obcaecati magnam assumenda eligendi praesentium quod? Accusantium, voluptate quo. Nam iure consequatur in provident!</p>
      </div>
    </main>

  </div>
);

export default About;
