import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import React, { useEffect, useState } from 'react';
import styles from '../styles/Home.module.css';

export default function Home() {
  const [blogs, setBlogs] = useState([]);

  const renderBlogs = async () => {
    let response = await fetch('/api/blogs/');
    let data = await response.json();
    let blogs = [];

    let idx = 0;
    for (const blog of data) {
      blogs.push(
        <div className={styles.blogItem} key={`blog_${idx++}`}>
          <Link href={`/blogpost/${blog.slug}`}>
            <h3 className={`${styles.link} ${styles['blogItem-h3']}`}>{blog.title}</h3>
          </Link>
          <p>
            {String(blog.content).slice(0, 54)}{'...'}
            <Link href={`/blogpost/${blog.slug}`}><span className={styles.readmore}>readmore</span></Link>
          </p>
        </div>
      )
    }

    setBlogs(blogs);
  };

  useEffect(() => {
    renderBlogs();
  }, []);

  return (
    <div className={styles.container}>
      <style jsx>
        {`
          h2 {
            font-size: 38px;
          }
          h3 {
            font-size: 28px;
          }
        `}
      </style>
      <Head>
        <title>Hunting Coders</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="nextjs, hunting coder, hunting coder blog" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Script src="/sc.js" strategy="lazyOnload"></Script> */}

      <main className={styles.main}>
        <h1 className={styles.title}>
          <span className="greating-span dummy">Welcome to</span>{' '}
          <a href="https://nextjs.org">Hunting Coders!</a>
        </h1>

        {/* <Image src="/coder.jpg" alt="" width={237} height={158} /> */}
        <div className={styles['image-wrap']}>
          <Image src="/coder.jpg" className={styles['home-coder-img']} width={435} height={290} />
        </div>

        <p className={styles.description}>
          A blog for hunting coders by a hunting coder
        </p>

        <div className="blogs">
          <h2>Latest Blogs</h2>
          {blogs}
        </div>

      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  );
};
