import Head from 'next/head';
import Image from 'next/image';
// import Link from 'next/link';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <style jsx>
        {`
          h2 {
            font-size: 38px;
          }
          h3 {
            font-size: 28px;
          }
        `}
      </style>
      <Head>
        <title>Hunting Coders</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="nextjs, hunting coder, hunting coder blog" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Script src="/sc.js" strategy="lazyOnload"></Script> */}

      <main className={styles.main}>
        <h1 className={styles.title}>
          <span className="greating-span dummy">Welcome to</span>{' '}
          <a href="https://nextjs.org">Hunting Coders!</a>
        </h1>

        {/* <Image src="/coder.jpg" alt="" width={237} height={158} /> */}
        <div className={styles['image-wrap']}>
          <Image src="/coder.jpg" className={styles['home-coder-img']} width={435} height={290} />
        </div>

        <p className={styles.description}>
          A blog for hunting coders by a hunting coder
        </p>

        <div className="blogs">
          <h2>Latest Blogs</h2>
          <div className="blogItem">
            <h3>How to learn JavaScript in 2022?</h3>
            <p>JavScript is the language used to design logic for the web</p>
          </div>
        </div>

      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  );
};
